wereRich = ["WE'RE RICH!"]

rockAndStone = [
    "ROCK ON!",
    "ROCK AND STONE... YEEAAAHHH!",
    "ROCK AND STONE FOREVER!",
    "ROCK. AND. STONE!",
    "ROCK AND STONE!",
    "ROCK AND STONE!",
    "FOR ROCK AND STONE!",
    "WE ARE UNBREAKABLE!",
    "ROCK AND ROLL!",
    "ROCK AND ROLL AND STONE!",
    "THAT'S IT LADS! ROCK AND STONE!",
    "LIKE THAT! ROCK AND STONE!",
    "YEAAHHH! ROCK AND STONE!",
    "NONE CAN STAND BEFORE US!", "ROCK SOLID!",
    "STONE AND ROCK! oh wait...",
    "COME ON GUYS! ROCK AND STONE!",
    "IF YA DON'T ROCK AND STONE, YOU AIN'T COMIN' HOME!",
    "WE FIGHT FOR ROCK AND STONE!",
    "WE ROCK!",
    "ROCK AND STONE EVERYONE!",
    "ROCK AND STONE IN THE HEART!",
    "DID I HEAR A ROCK AND STONE?",
    "ROCK AND STONE!",
    "ROCK AND STONE!",
    "ROCK AND STONE, BROTHER!",
    "ROCK AND STONE TO THE BONE!",
    "FOR KARL!",
    "LEAVE NO DWARF BEHIND!",
    "BY THE BEARD!",
    "LET'S ROCK AND STONE!",
    "last one to rock and stone pays for the first round!",
    "ROCK AND STONE! it never gets old",
    "ROCK ME LIKE A STONE!",
    "IF YA ROCK AND STONE, YOU'RE NEVER ALONE!",
    "GIVE ME A ROCK AND STONE!",
    "ROCK AND STONE, THE PRETTY SOUND OF TEAMWORK!",
    "ROCK AND STONE LIKE THERE'S NO TOMORROW!",
    "if I had a credit for every rock and stone...",
    "WE'RE THE BEST!",
    "GIMME AN R! GIMME AN S! GIMME A ROCK AND STONE!",
    "ROCKITY ROCK AND STONE!",
    "ROCK AND STONE YOU BEAUTIFUL DWARF!",
    "for those about to rock and stone, we salute you!",
    "ROCK *burp* AND *burp* STONE! *burp*",
    "GALAXY'S FINEST!",
    "are we rocks, stones, or both?"

]